import { Scissors, Download, FileText } from 'lucide-react';
import { useProjectStore } from '@/store/projectStore';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { toast } from 'sonner';

export const CutListPanel = () => {
  const { pieces, getCutList, projectName } = useProjectStore();
  const cutList = getCutList();

  const totalPieces = pieces.length;
  
  const handleExport = () => {
    const content = generateCutListText();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName.replace(/\s+/g, '_')}_cut_list.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Cut list exported successfully!');
  };

  const generateCutListText = () => {
    let content = `CUT LIST - ${projectName}\n`;
    content += `${'='.repeat(50)}\n\n`;
    content += `Total Pieces: ${totalPieces}\n\n`;
    content += `LUMBER REQUIRED:\n`;
    content += `${'-'.repeat(30)}\n\n`;

    cutList.forEach((item) => {
      content += `${item.lumberType}\n`;
      content += `  Quantity: ${item.quantity}\n`;
      content += `  Length: ${item.length}"\n\n`;
    });

    content += `\n${'='.repeat(50)}\n`;
    content += `Generated by WoodCraft Studio\n`;
    content += `Date: ${new Date().toLocaleDateString()}\n`;

    return content;
  };

  if (pieces.length === 0) {
    return (
      <div className="panel h-48 animate-fade-in">
        <div className="panel-header">
          <Scissors size={16} />
          <span>Cut List</span>
        </div>
        <div className="p-4 text-center text-muted-foreground">
          <FileText size={24} className="mx-auto mb-2 opacity-50" />
          <p className="text-sm">Add lumber to see cut list</p>
        </div>
      </div>
    );
  }

  return (
    <div className="panel flex flex-col animate-fade-in" style={{ maxHeight: '300px' }}>
      <div className="panel-header justify-between">
        <div className="flex items-center gap-2">
          <Scissors size={16} />
          <span>Cut List</span>
        </div>
        <span className="text-xs bg-primary/20 text-primary px-2 py-0.5 rounded-full">
          {totalPieces} pieces
        </span>
      </div>

      <ScrollArea className="flex-1 p-3">
        <div className="space-y-2">
          {cutList.map((item, index) => (
            <div key={index} className="cut-list-item">
              <div className="flex justify-between items-start">
                <div>
                  <p className="font-medium">{item.lumberType}</p>
                  <p className="text-xs text-muted-foreground">
                    Length: {item.length}"
                  </p>
                </div>
                <span className="text-primary font-bold">×{item.quantity}</span>
              </div>
            </div>
          ))}
        </div>
      </ScrollArea>

      <div className="p-3 border-t border-border">
        <Button
          variant="secondary"
          size="sm"
          className="w-full"
          onClick={handleExport}
        >
          <Download size={14} className="mr-2" />
          Export Cut List
        </Button>
      </div>
    </div>
  );
};
